sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t namsick96/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true namsick96/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react-app2
  env: Dockerreactapp2-env
  bucket_name: elasticbeanstalk-ap-northeast-2-807459427734
  bucket_path: docker-react-app2
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
