sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t namsick96/docker-react-app:latest -f Dockerfile.dev

script:
  - docker run -e CI=true namsick96/docker-react-app npm run test -- --coverage

after_sucess:
  - echo "Test Success"
